version: '3.7'

services:
  postgres:
    image: "postgres:11.5-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=techselect
      - POSTGRES_PASSWORD=techselect
  drools:
    image: jboss/drools-workbench-showcase:latest
    ports:
      - 9090:8080
      - 8001:8001