server:
  port: ${PORT:8080}
spring:
  application:
    name: techselect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgres://localhost:5432/techselect}
    username: ${SPRING_DATASOURCE_USERNAME:techselect}
    password: ${SPRING_DATASOURCE_PASSWORD:techselect}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: techselect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: techselect
    locations: classpath:db/migration
    baseline-on-migrate: true