server:
  port: ${PORT:8080}
spring:
  application:
    name: techselect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techselect}
    username: ${SPRING_DATASOURCE_USERNAME:techselect}
    password: ${SPRING_DATASOURCE_PASSWORD:techselect}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      default_schema: techselect
  flyway:
    schemas: techselect
    locations: classpath:db/migration
    baseline-on-migrate: true