spring:
  datasource:
    url: jdbc:tc:postgresql:11://localhost:5432/techselect
    username: techselect
    password:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    locations: classpath:db/migration,classpath:db/testdata